### ISSUE TITLE
Test against the different integrations more easily locally

### ISSUE THREAD

**Issue by tombruijn** [appsignal/diagnose_tests#33]
I need to push and pull to the diagnose tests repo a lot to test the changes I made in the diagnose tests and integrations. I'd like a way to easily run this locally.

```
cd ~/appsignal/diagnose_tests
LANGUAGE=elixir bin/test
LANGUAGE=nodejs bin/test
LANGUAGE=ruby bin/test
```

**Comment by unflxw** [comment]
@tombruijn do we consider that #40 closes this, or does it need further improvement?

**Comment by tombruijn** [comment]
No, #40 closes this!
